### ISSUE TITLE
Issue when running setup.sh

### ISSUE THREAD

**Issue by MNoorAlRashdan** [felicitywang/TFMTL#1]
when I run setup.sh from the expts/example directory, after a couple of time of execution I get the following error:
[Errno 2] No such file or directory: 'data/tf/single/SSTb/min_1_max_-1_vocab_-1_doc_-1_tok_tweet/'
Furthermore, when I create the folder by myself I get the following error:
File "../scripts/write_tfrecords_finetune.py", line 123, in <module>
    main()
  File "../scripts/write_tfrecords_finetune.py", line 62, in main
    args_path = os.path.join(vocab_dir, os.listdir(vocab_dir)[0],
IndexError: list index out of range

Please advice.

**Comment by felicitywang** [comment]
Hi @MNoorAlRashdan `setup.sh` lists some example scripts of different steps in `expts/README.md`. You didn't post the full results: which command triggered this error, and do you know what should be in the folder? File structure and data creation instructions are also included in the READMEs.
